### PR TITLE
Update branch name for SPM to `feature/SPM`

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by melekr** [comment]
Hi @ohayon, thank you for submitting these changes.

branch: "SwiftPM" and branch: "feature/SwiftPM" should behave the same, 
did you encounter any issues with this?

**Comment by ohayon** [comment]
yeah, adding the package in Xcode (not in a Package.swift file) without `feature/` failed to download the package.

**Comment by melekr** [comment]
Both variations resolve on my end, accepting this thank you @ohayon

**Review by melekr — COMMENTED** [review]
good to go!

**Pull request merged**
