### PR TITLE
Update deploy.yml

### PR DESCRIPTION
**Pull request by melekr**
- Disable building dynamic frameworks

### CODE REVIEW

**Review by konraddysput — APPROVED** [review]

**Comment by vlussenburg** [comment]
@melekr Noooooooo! :) 

Hi, I'm Vincent, a previous maintainer of this library :)

This took lots of time and was used by various customers. The tickets can be found in hack for it, I remember a big name customer specifically asking for it and it being prioritized via Zendesk as well. Are you certain you want to remove it?

**Comment by vlussenburg** [comment]
(and if you're certain you may want to remove `.github/workflows/Podfile` as well)

**Comment by melekr** [comment]
@vlussenburg Hi Vincent 👋🏽 Nice to finally virtually meet you!

We've encountered some issues building these static frameworks that why we disabled them.

- Bitcode is now officially deprecated and [submissions to the AppStore with Bitcode](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes) are no longer accepted.
- A recent [Cocoapod issue](https://github.com/CocoaPods/CocoaPods/issues/11839) is keeping us from building static libraries the way we use to, we're closely monitoring the open issue.

Now that we have SPM, we're thinking about shifting those customers towards SPM where they can build our library however they like (dynamically or statically) for any architecture of their liking.

Please do let me know if I missed something, really appreciate the feedback :)

**Comment by rick-bt** [comment]
Thank you @vlussenburg - you seem to have ascended from "maintainer" to "guardian angel". Reassuring! :)

**Pull request merged**
