### PR TITLE
Error should be a broken heart 💔

### PR DESCRIPTION
**Pull request by diemol**
Please consider this, a red heart is meant for beautiful things, but a 💔 is more suited to log an error.

### CODE REVIEW

**Comment by kristofmuhi** [comment]
agreed

**Comment by konraddysput** [comment]
thanks @diemol - I assigned the right persons to check and merge it to our code base. Thank you!

**Comment by konst-sauce** [comment]
No objections 👍

**Comment by diemol** [comment]
Hm, I do not see how failures in the `ios` job are related to the PR. Is there something I can do to help?

**Review by vlussenburg — APPROVED** [review]

**Comment by vlussenburg** [comment]
> Hm, I do not see how failures in the `ios` job are related to the PR. Is there something I can do to help?

I reran them. There's some flaky tests in there. all good!

**Comment by diemol** [comment]
Thank you, @vlussenburg!

**Pull request merged**
